
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Sun Jan 18 11:19:15 CET 2015
//----------------------------------------------------

package parser;

/** CUP generated interface containing symbol constants. */
public interface Symbols {
  /* terminals */
  public static final int GROUP_AS = 38;
  public static final int FORALL = 33;
  public static final int DIVIDE = 10;
  public static final int STRING_LITERAL = 5;
  public static final int MORE_OR_EQUAL = 15;
  public static final int EQUALS = 12;
  public static final int XOR = 24;
  public static final int MINUS_FUNCTION = 41;
  public static final int FORANY = 34;
  public static final int LESS = 17;
  public static final int MINUS = 8;
  public static final int WHERE = 32;
  public static final int BOOLEAN_LITERAL = 2;
  public static final int NOT = 39;
  public static final int AND = 23;
  public static final int LESS_OR_EQUAL = 16;
  public static final int IN = 21;
  public static final int OR = 22;
  public static final int COMMA = 20;
  public static final int BAG = 35;
  public static final int PLUS = 7;
  public static final int MULTIPLY = 9;
  public static final int MIN = 29;
  public static final int DOT = 19;
  public static final int LEFT_ROUND_BRACKET = 43;
  public static final int EOF = 0;
  public static final int error = 1;
  public static final int MODULO = 11;
  public static final int EXISTS = 40;
  public static final int JOIN = 18;
  public static final int UNIQUE = 27;
  public static final int AVG = 26;
  public static final int UNION = 28;
  public static final int NOT_EQUALS = 13;
  public static final int SUM = 25;
  public static final int DOUBLE_LITERAL = 4;
  public static final int INTERSECT = 42;
  public static final int AS = 37;
  public static final int COUNT = 31;
  public static final int STRUCT = 36;
  public static final int MAX = 30;
  public static final int MORE = 14;
  public static final int RIGHT_ROUND_BRACKET = 44;
  public static final int INTEGER_LITERAL = 3;
  public static final int IDENTIFIER = 6;
}

